name: xcvbnm
version: 0.0.1
author: Werner Gaisbauer @ Exit Live, alex@tekartik.com
description: This is intended as a Dart port of zxcvbn (see https://github.com/dropbox/zxcvbn).
environment:
  sdk: '>=1.9.0 <2.0.0'
dependencies:

dev_dependencies:
  test: ^0.12.0
  browser: any
